language: Java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
- ./gradlew sonarqube
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: heroku
  api_key:
    secure: ANJdNTEseWB/zuNVO38DHwa+KWyjudZI7Ih1eK5wMvMlDPQ4xQOisqXy4IPRT34l7+T2KEWYVYqirPvhC10gxV8WxyVnY2Rxna5ArI4/eytSjuI9pALnNYX9z4wEpZpKnzpUedY3gkBMtYhbYsMrgHJ/ZFLA2cJBOHM4kQSwEet3x2x+5sap2JxC6Svcmujw3V286h4xVO2NNViyIhOgIuc/As5/e8vP1KKHZGQjNJBgPOyX39GFYTlCZoA7Bj7OlTKSgrwizyjh46skQ/HgIb4q/P38Vr7SjkTxDXo+/HeRQ1wvJ9N+t6mQ1OfA5YkaV+/r/0oXsGsz8ot8RNiIf9k1hptt82aEGc4lOaj91M9zOOzGbp+ZDmuiTSHiHBgEjXm0oATUgFBQF0MI51GhOwnEcw8c8mvpeyZpj2y/LWXsEjMrEiW2N3nnSlM5NopoL7wOGSgcZcr8zW8zpOWYgSuHgw/sK5cfpEu3LiA14wYV0BE0LePr0Y7aYynyZREYdzKcLXIJYo7yE+0CG7CWw6SnOuDebD6g/1bTfIgZVlg2KweelAWcs0zMZi4mznDbxvgVvV/o6wRlEDClvYNPM1VU9OcCfiQOyZ1tCHlMB5PYTTlNYarDniS5xoD9v3SkgHBjveXCKVKmV71i1JpZIe9KbJ6k1ZvFyFIXTLdOZLY=
  app: confirmation-service-staging
  on:
    repo: spolnik/trading-office-confirmation-service
services:
- mongodb