server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000/eureka/}
---
spring:
  profiles: heroku
  data:
      mongodb:
        uri: ${MONGOLAB_URI}
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
